version: "3.1"

services:
    redis:
        image: redis:alpine
        container_name: ${APP_NAME}-redis
        tty: true
        environment:
            - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        networks:
            - Laravel11

    node:
        image: node
        container_name: ${APP_NAME}-node
        tty: true
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
            - "5173:5173"
        networks:
            - Laravel11

    db:
        image: postgres:latest
        container_name: ${APP_NAME}-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - Laravel11

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - Laravel11

    php:
        build: _docker/php-fpm
        image: nurgaliseidazimov/laravel11-app-image:v1.0.0
        container_name: ${APP_NAME}-php-fpm
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            #- ./_docker/php-fpm/php.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
            - ./_docker/supervisor:/etc/supervisor/conf.d/
        ports:
            - "9000:9000"
            - "8080:8080"
        networks:
            - Laravel11

networks:
    Laravel11:
        driver: bridge

volumes:
    db-data:
