version: "3.1"

services:
#    redis:
#        image: redis:alpine
#        container_name: ${APP_NAME}-redis
#        tty: true
#        environment:
#            - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
#        networks:
#            - internal

    node:
        image: node
        container_name: ${APP_NAME}-node
        tty: true
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
            - "5173:5173"
        networks:
            - internal

#    db:
#        image: postgres:latest
#        container_name: ${APP_NAME}-postgres
#        restart: unless-stopped
#        environment:
#            - POSTGRES_DB=${DB_DATABASE}
#            - POSTGRES_USER=${DB_USERNAME}
#            - POSTGRES_PASSWORD=${DB_PASSWORD}
#        volumes:
#            - ./tmp/db:/var/lib/postgresql/data
#        ports:
#            - "5432:5432"
#        networks:
#            - internal

    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}-nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - internal

    php:
        build: _docker/php-fpm
        container_name: ${APP_NAME}-php-fpm
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            #- ./_docker/php-fpm/php.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        ports:
            - ":9000"
        networks:
            - internal

networks:
    internal:
        driver: bridge
