name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Установка Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Установка Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Кеширование Docker слоев
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Сборка и запуск Docker контейнеров
      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      # Тестирование
      - name: Run tests
        run: |
          docker-compose exec Laravel11-php-fpm ./vendor/bin/phpunit

      - name: Docker down
        run: |
          docker-compose down
